public enum FlatSharpConflictResolution {
	CHOOSE_LESS_SHIFTS_IFEQ_SHARP,
	CHOOSE_LESS_SHIFTS_IFEQ_FLAT,
	CHOOSE_SHARPS_IFEQ_SHARP,
	CHOOSE_SHARPS_IFEQ_FLAT,
	CHOOSE_FLATS_IFEQ_FLAT,
	CHOOSE_FLATS_IFEQ_SHARP;
}
